### ISSUE TITLE
Compatibility with FOSS CL implementations

### ISSUE THREAD

**Issue by peterhoeg** [e40/tget#1]
tget looks really neat, but without compatibility with one (or more) of the various free and open source CL implementations, it's going to be rather hard getting started with it.

Any chance you want to consider adding support for that?

**Comment by e40** [comment]
Unfortunately, I'm an ACL user and don't use SBCL or CMUCL, so this is unlikely. I have no idea of the amount of work it would be, honestly. It depends on some ACL tools  (xml sax parser, for one) that I don't know anything about the FOSS alternatives.  And, I don't really have much time to work on ports.  Sorry.
